// <auto-generated />
using System;
using DWAApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DWAApi.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231116154038_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DWAApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DWAApi.Models.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CircleCalf")
                        .HasColumnType("integer");

                    b.Property<int>("CircleChest")
                        .HasColumnType("integer");

                    b.Property<int>("CircleHip")
                        .HasColumnType("integer");

                    b.Property<int>("EUSizeL")
                        .HasColumnType("integer");

                    b.Property<int>("EUSizeS")
                        .HasColumnType("integer");

                    b.Property<int>("EUSizeT")
                        .HasColumnType("integer");

                    b.Property<string>("SkinColour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("DWAApi.Models.User", b =>
                {
                    b.HasOne("DWAApi.Models.UserInfo", "UserInfo")
                        .WithOne("User")
                        .HasForeignKey("DWAApi.Models.User", "UserInfoId");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("DWAApi.Models.UserInfo", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
