// <auto-generated />
using System;
using DWAApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DWAApi.Data;

#nullable disable

namespace DWAApi.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231022063325_ORM-update3")]
    partial class ORMupdate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WBAApi.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WBAApi.Models.UserInfo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("CircleCalf")
                        .HasColumnType("integer");

                    b.Property<int>("CircleChest")
                        .HasColumnType("integer");

                    b.Property<int>("CircleHip")
                        .HasColumnType("integer");

                    b.Property<int>("EUSizeL")
                        .HasColumnType("integer");

                    b.Property<int>("EUSizeS")
                        .HasColumnType("integer");

                    b.Property<int>("EUSizeT")
                        .HasColumnType("integer");

                    b.Property<string>("SkinColour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("WBAApi.Models.UserInfo", b =>
                {
                    b.HasOne("WBAApi.Models.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("WBAApi.Models.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WBAApi.Models.User", b =>
                {
                    b.Navigation("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
